"""初始迁移：daily_bars + pattern_signals

Revision ID: 2b2d7a68c2bf
Revises: 
Create Date: 2026-05-31 14:06:41.441440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b2d7a68c2bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_daily_bars_code_date'), table_name='daily_bars')
    op.create_index(op.f('ix_daily_bars_code'), 'daily_bars', ['code'], unique=False)
    op.create_index(op.f('ix_daily_bars_date'), 'daily_bars', ['date'], unique=False)
    op.alter_column('pattern_signals', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.drop_index(op.f('idx_pattern_signals_code_date'), table_name='pattern_signals')
    op.drop_index(op.f('idx_pattern_signals_pattern'), table_name='pattern_signals')
    op.create_index(op.f('ix_pattern_signals_code'), 'pattern_signals', ['code'], unique=False)
    op.create_index(op.f('ix_pattern_signals_date'), 'pattern_signals', ['date'], unique=False)
    op.create_index(op.f('ix_pattern_signals_pattern_id'), 'pattern_signals', ['pattern_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_signals_pattern_id'), table_name='pattern_signals')
    op.drop_index(op.f('ix_pattern_signals_date'), table_name='pattern_signals')
    op.drop_index(op.f('ix_pattern_signals_code'), table_name='pattern_signals')
    op.create_index(op.f('idx_pattern_signals_pattern'), 'pattern_signals', ['pattern_id', 'date'], unique=False)
    op.create_index(op.f('idx_pattern_signals_code_date'), 'pattern_signals', ['code', 'date'], unique=False)
    op.alter_column('pattern_signals', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.drop_index(op.f('ix_daily_bars_date'), table_name='daily_bars')
    op.drop_index(op.f('ix_daily_bars_code'), table_name='daily_bars')
    op.create_index(op.f('idx_daily_bars_code_date'), 'daily_bars', ['code', 'date'], unique=False)
    # ### end Alembic commands ###
